# Site settings
title: Christophe Penhard
name: Christophe Penhard
email: "cpenhard (at) yahoo (dot) fr" 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://christophepen.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["node_modules", "_css", "package.json"]
collections:
  projects:
    output: true

# Prose settings
prose:
  rooturl: '_projects'
  siteurl: 'http://christophepenhard.com/'
  relativeLinks: 'http://christophepenhard.com/links.jsonp'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _projects:
      - name: "category"
        field:
          element: "hidden"
          value: "project"
      - name: "layout"
        field:
          element: "hidden"
          value: "project"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "cover"
        field:
          element: "text"
          label: "Cover image"
          value: ""
